/**
 * ReportExport — the PDF download card in the reports tab.
 *
 * What these tests protect:
 *
 *  1. The chosen period and reference date reach the API unchanged (asking for
 *     July and getting August is worse than an error).
 *  2. A failure surfaces as a message instead of a silent no-op download.
 *  3. pdf-lib is only imported when someone actually exports.
 */

import { describe, it, expect, vi, beforeEach } from 'vitest'
import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { ReportExport } from './ReportExport'

const { getOverviewReportMock, generateReportPDFMock, reportFilenameMock, downloadPDFMock, toastMock } = vi.hoisted(
  () => ({
    getOverviewReportMock: vi.fn(),
    generateReportPDFMock: vi.fn(),
    reportFilenameMock: vi.fn(),
    downloadPDFMock: vi.fn(),
    toastMock: { success: vi.fn(), error: vi.fn() },
  })
)

vi.mock('../../lib/reports', () => ({ getOverviewReport: getOverviewReportMock }))
vi.mock('../../lib/report-pdf', () => ({
  generateReportPDF: generateReportPDFMock,
  reportFilename: reportFilenameMock,
}))
vi.mock('../../lib/contract-generator', () => ({ downloadPDF: downloadPDFMock }))
vi.mock('sonner', () => ({ toast: toastMock }))

const fakeReport = { period: { type: 'month', start: '2026-08-01T00:00:00.000Z' } }

describe('ReportExport', () => {
  beforeEach(() => {
    vi.clearAllMocks()
    getOverviewReportMock.mockResolvedValue(fakeReport)
    generateReportPDFMock.mockResolvedValue(new Uint8Array([1, 2, 3]))
    reportFilenameMock.mockReturnValue('relatorio-geekpop-month-2026-08.pdf')
  })

  it('defaults to the monthly closing', async () => {
    render(<ReportExport />)

    expect(screen.getByRole('button', { name: 'Mês' })).toHaveAttribute('aria-pressed', 'true')
    expect(screen.getByRole('button', { name: 'Dia' })).toHaveAttribute('aria-pressed', 'false')
  })

  it('sends the chosen period and date to the API', async () => {
    render(<ReportExport />)

    await userEvent.click(screen.getByRole('button', { name: 'Ano' }))
    const dateInput = screen.getByLabelText('Data de referência')
    await userEvent.clear(dateInput)
    await userEvent.type(dateInput, '2026-07-15')
    await userEvent.click(screen.getByRole('button', { name: /Baixar PDF/i }))

    await waitFor(() => expect(getOverviewReportMock).toHaveBeenCalledWith('year', '2026-07-15'))
  })

  it('hands the generated bytes to the downloader under the report filename', async () => {
    render(<ReportExport />)

    await userEvent.click(screen.getByRole('button', { name: /Baixar PDF/i }))

    await waitFor(() => expect(downloadPDFMock).toHaveBeenCalled())
    expect(generateReportPDFMock).toHaveBeenCalledWith(fakeReport)
    expect(downloadPDFMock).toHaveBeenCalledWith(new Uint8Array([1, 2, 3]), 'relatorio-geekpop-month-2026-08.pdf')
    expect(toastMock.success).toHaveBeenCalled()
  })

  it('does not touch pdf-lib until someone exports', async () => {
    render(<ReportExport />)

    expect(generateReportPDFMock).not.toHaveBeenCalled()
  })

  it('surfaces a failed report instead of downloading nothing', async () => {
    getOverviewReportMock.mockRejectedValue(new Error('Não foi possível carregar o relatório'))
    render(<ReportExport />)

    await userEvent.click(screen.getByRole('button', { name: /Baixar PDF/i }))

    await waitFor(() => expect(toastMock.error).toHaveBeenCalledWith('Não foi possível carregar o relatório'))
    expect(downloadPDFMock).not.toHaveBeenCalled()
  })

  it('re-enables the button after a failure', async () => {
    generateReportPDFMock.mockRejectedValue(new Error('pdf quebrou'))
    render(<ReportExport />)

    await userEvent.click(screen.getByRole('button', { name: /Baixar PDF/i }))

    await waitFor(() => expect(toastMock.error).toHaveBeenCalled())
    expect(screen.getByRole('button', { name: /Baixar PDF/i })).toBeEnabled()
  })
})
